In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import plotly.graph_objects as go

snp = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "investing_dot_com_transformed" / "CSPX ETF Stock Price History.csv")
china = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "investing_dot_com_transformed" / "CNYA ETF Stock Price History.csv")
em = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "investing_dot_com_transformed" / "EIMI ETF Stock Price History.csv")
gold = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "investing_dot_com_transformed" / "XAD5 ETF Stock Price History.csv")
india = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "investing_dot_com_transformed" / "INR ETF Stock Price History.csv")
mscieurope = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "investing_dot_com_transformed" / "XMEU ETF Stock Price History.csv")
smallcapeurope = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "investing_dot_com_transformed" / "SXRJ ETF Stock Price History.csv")
ussmallcap = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "investing_dot_com_transformed" / "CUSS ETF Stock Price History.csv")
silver = pd.read_csv(Path.cwd().parent / "data" / "OHCL" / "investing_dot_com_transformed" / "SSLN ETF Stock Price History.csv")

dfs = [snp, china, em, gold, india, mscieurope, smallcapeurope, ussmallcap, silver]

N = len(dfs)
T = len(dfs[0]) - 1

dfs = [df[["Date", "Price", "Vol."]] for df in dfs]

# Convert Date to datetime
dfs_new = []
for df in dfs:
    df["Date"] = pd.to_datetime(df["Date"])
    dfs_new.append(df)

dfs = dfs_new

names = ["snp", "china", "em", "gold", "india", "mscieurope",
         "smallcapeurope", "ussmallcap", "silver"]

dfs_renamed = []

for name, df in zip(names, dfs):
    df = df.copy()
    df["Date"] = pd.to_datetime(df["Date"])
    
    df = df.rename(columns={
        "Price": f"Price_{name}",
        "Vol.": f"Vol_{name}"
    })
    
    dfs_renamed.append(df)

dfs = dfs_renamed

# Merge all on Date
df_merged = dfs[0]
for df in dfs[1:]:
    df_merged = df_merged.merge(df, on="Date", how="inner", suffixes=("", "_x"))

# Sort by date
df_merged = df_merged.sort_values("Date")

def correct_volume(vol_value):
    if isinstance(vol_value, (float, int)):
        return vol_value
    if vol_value[-1] == "K":
        return 1000 * float(vol_value[:-1])
    if vol_value[-1] == "M":
        return 1_000_000 * float(vol_value[:-1])
    return float(vol_value)

df_merged = df_merged.set_index("Date")

price_cols = [col for col in df_merged.columns if col.startswith("Price_")]
vol_cols = [col for col in df_merged.columns if col.startswith("Vol_")]

prices_df = df_merged[price_cols].apply(pd.to_numeric, errors="coerce")
volumes_df = df_merged[vol_cols].copy()

for col in volumes_df.columns:
    volumes_df[col] = volumes_df[col].apply(correct_volume)

volumes_df = volumes_df.fillna(0.0)

prices = prices_df.values  # shape: (T+1, N)
volumes = volumes_df.values  # shape: (T+1, N)

returns = prices[1:] / prices[:-1] - 1
prices = prices[1:]
volumes = volumes[1:]         # (T, N)
dates = df_merged.index[1:]       # (T,)
print(returns.shape, prices.shape, volumes.shape, dates.shape)

(2413, 9) (2413, 9) (2413, 9) (2413,)

In [2]:
graph = go.Figure()
for i in range(returns.shape[1]):
    L = list(range(T))
    cum_returns = np.cumprod(1 + returns[:,i]) - 1
    graph.add_trace(go.Scatter(x=dates, y=cum_returns, name=names[i]))
graph.show()

In [3]:
# ETFs spreads (bps) - estimated
etf_spreads = np.array([0.0075, 0.050, 0.100, 0.035, 0.130, 0.030, 0.030, 0.050, 0.08]) / 100
risk_free = 0.03
alpha = 0.05   # tail probability for CVaR
lambda_ = 0.5  # CVaR penalty
gamma = 0.08
weight_diff_rebalance = 0.10 # minimum weight difference for a portfolio rebalance
window_size = 252
validation_size = 252
m_params = np.array([0.33, 0.33, 0.33])
stress_corr_weight = 0.5
max_cash_alloc = 0.3
cash_alloc_param = 0.5
min_weight = 0.1
stepsize = 50

In [4]:
from rollingwindow_and_eval import rolling_window

df, total_costs, total_stress_values, track_pct_rebalances, track_cash_allocs = rolling_window(
    returns, volumes, prices,
     window_size, stepsize, validation_size,
     gamma, alpha, lambda_,
    m_params, risk_free, etf_spreads, weight_diff_rebalance,
    stress_corr_weight, max_cash_alloc, cash_alloc_param, min_weight
    )

df

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/resource_handle.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor_shape.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/types.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/full_type.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/function.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/node_def.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/op_def.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/graph.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/graph_debug_info.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/versions.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/protobuf/config.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at xla/tsl/protobuf/coordination_config.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/cost_graph.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/step_stats.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/allocation_description.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor_description.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/protobuf/cluster.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

C:\Users\tobia\AppData\Roaming\Python\Python311\site-packages\google\protobuf\runtime_version.py:98: UserWarning:

Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/protobuf/debug.proto. Please update the gencode to avoid compatibility violations in the next runtime release.

DISTANCE:
[[0.00000000e+00 5.17512502e-01 3.00324379e-01 7.53067446e-01
  3.76657504e-01 2.95801297e-01 3.11543006e-01 1.88633114e-01
  7.05768429e-01]
 [5.17512502e-01 0.00000000e+00 4.64452259e-01 6.97863948e-01
  5.37388043e-01 5.42838204e-01 5.48180319e-01 5.41251175e-01
  6.52216586e-01]
 [3.00324379e-01 4.64452259e-01 0.00000000e+00 7.30760055e-01
  3.67681921e-01 3.37853414e-01 3.48014181e-01 3.24677398e-01
  6.74229621e-01]
 [7.53067446e-01 6.97863948e-01 7.30760055e-01 0.00000000e+00
  6.96541780e-01 7.71943920e-01 7.95749914e-01 7.54093472e-01
  3.89184262e-01]
 [3.76657504e-01 5.37388043e-01 3.67681921e-01 6.96541780e-01
  0.00000000e+00 4.13881981e-01 3.84046984e-01 4.23499347e-01
  7.08882434e-01]
 [2.95801297e-01 5.42838204e-01 3.37853414e-01 7.71943920e-01
  4.13881981e-01 0.00000000e+00 2.80266097e-01 3.30765334e-01
  6.86978699e-01]
 [3.11543006e-01 5.48180319e-01 3.48014181e-01 7.95749914e-01
  3.84046984e-01 2.80266097e-01 7.45058060e-09 3.33761649e-01
  7.71291823e-01]
 [1.88633114e-01 5.41251175e-01 3.24677398e-01 7.54093472e-01
  4.23499347e-01 3.30765334e-01 3.33761649e-01 7.45058060e-09
  7.06043562e-01]
 [7.05768429e-01 6.52216586e-01 6.74229621e-01 3.89184262e-01
  7.08882434e-01 6.86978699e-01 7.71291823e-01 7.06043562e-01
  1.05367121e-08]]
PRINTING STATS

Mean daily return: 0.0006205334154330245
Annualized mean return: 0.15823602093542125
Daily std: 0.004266344692192792
Annualized std: 0.06812806135002969
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15811837387659772
Sharpe ratio: 2.32089935840408
PRINTING STATS

Mean daily return: 0.0006205334154330245
Annualized mean return: 0.15823602093542125
Daily std: 0.004266344692192792
Annualized std: 0.06812806135002969
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15811837387659772
Sharpe ratio: 2.32089935840408
PRINTING STATS

Mean daily return: 0.0005517709021505778
Annualized mean return: 0.14070158004839733
Daily std: 0.004455042064138197
Annualized std: 0.0711413167384213
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.1405839329895738
Sharpe ratio: 1.9761221669045748
PRINTING STATS

Mean daily return: 0.0005517910663270491
Annualized mean return: 0.14070672191339753
Daily std: 0.004454113231421849
Annualized std: 0.07112648446938336
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.140589074854574
Sharpe ratio: 1.9766065468214034
PRINTING STATS

Mean daily return: 0.0005744425163678643
Annualized mean return: 0.14648284167380538
Daily std: 0.004497442737580163
Annualized std: 0.07181840119594837
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.14636519461498185
Sharpe ratio: 2.0379901554149193
PRINTING STATS

Mean daily return: 0.0005744163188357711
Annualized mean return: 0.14647616130312163
Daily std: 0.00449759837202646
Annualized std: 0.0718208864787538
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.1463585142442981
Sharpe ratio: 2.037826618689734
PRINTING STATS

Mean daily return: 0.0006205334154330245
Annualized mean return: 0.15823602093542125
Daily std: 0.004266344692192792
Annualized std: 0.06812806135002969
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15811837387659772
Sharpe ratio: 2.32089935840408
PRINTING STATS

Mean daily return: 0.0006205334154330245
Annualized mean return: 0.15823602093542125
Daily std: 0.004266344692192792
Annualized std: 0.06812806135002969
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15811837387659772
Sharpe ratio: 2.32089935840408
PRINTING STATS

Mean daily return: 0.0006205334154330245
Annualized mean return: 0.15823602093542125
Daily std: 0.004266344692192792
Annualized std: 0.06812806135002969
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15811837387659772
Sharpe ratio: 2.32089935840408
DISTANCE:
[[0.00000000e+00 6.05962766e-01 4.53196388e-01 7.52099572e-01
  4.86393381e-01 4.84661105e-01 4.25968414e-01 2.88865778e-01
  7.12624348e-01]
 [6.05962766e-01 0.00000000e+00 5.48034090e-01 7.04873138e-01
  6.10097940e-01 6.75221716e-01 6.73038114e-01 6.18933186e-01
  6.92546373e-01]
 [4.53196388e-01 5.48034090e-01 1.05367121e-08 6.76495081e-01
  4.52934190e-01 4.91589311e-01 4.68169653e-01 5.27887152e-01
  6.24526339e-01]
 [7.52099572e-01 7.04873138e-01 6.76495081e-01 0.00000000e+00
  6.81336776e-01 7.35042341e-01 7.32365527e-01 7.38959162e-01
  3.85922625e-01]
 [4.86393381e-01 6.10097940e-01 4.52934190e-01 6.81336776e-01
  7.45058060e-09 5.13373735e-01 4.66389530e-01 5.21943066e-01
  7.07192236e-01]
 [4.84661105e-01 6.75221716e-01 4.91589311e-01 7.35042341e-01
  5.13373735e-01 0.00000000e+00 4.04291057e-01 5.60564097e-01
  6.27705549e-01]
 [4.25968414e-01 6.73038114e-01 4.68169653e-01 7.32365527e-01
  4.66389530e-01 4.04291057e-01 0.00000000e+00 4.79680997e-01
  7.22698822e-01]
 [2.88865778e-01 6.18933186e-01 5.27887152e-01 7.38959162e-01
  5.21943066e-01 5.60564097e-01 4.79680997e-01 1.05367121e-08
  7.24894153e-01]
 [7.12624348e-01 6.92546373e-01 6.24526339e-01 3.85922625e-01
  7.07192236e-01 6.27705549e-01 7.22698822e-01 7.24894153e-01
  1.05367121e-08]]
PRINTING STATS

Mean daily return: 4.383095016058813e-05
Annualized mean return: 0.011176892290949973
Daily std: 0.0074217820461840575
Annualized std: 0.11851635511173259
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.011059245232126444
Sharpe ratio: 0.09331408497755622
PRINTING STATS

Mean daily return: 4.3597205731207084e-05
Annualized mean return: 0.011117287461457806
Daily std: 0.0074402687081453235
Annualized std: 0.11881156342965381
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.010999640402634276
Sharpe ratio: 0.09258055432581666
PRINTING STATS

Mean daily return: 7.522236322395594e-05
Annualized mean return: 0.019181702622108762
Daily std: 0.008100408980137183
Annualized std: 0.12935315821269774
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.019064055563285234
Sharpe ratio: 0.1473799003186135
PRINTING STATS

Mean daily return: 7.52218118824078e-05
Annualized mean return: 0.019181562030013987
Daily std: 0.008100558910104238
Annualized std: 0.1293555524022747
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.01906391497119046
Sharpe ratio: 0.1473760856581153
PRINTING STATS

Mean daily return: 0.0001634217680254081
Annualized mean return: 0.04167255084647906
Daily std: 0.00831896611396913
Annualized std: 0.13284323576068333
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.041554903787655535
Sharpe ratio: 0.3128115899142698
PRINTING STATS

Mean daily return: 0.0001633869684058693
Annualized mean return: 0.04166367694349667
Daily std: 0.008318846843603232
Annualized std: 0.13284133116567487
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.041546029884673145
Sharpe ratio: 0.3127492740407611
PRINTING STATS

Mean daily return: 6.280011682778087e-05
Annualized mean return: 0.01601402979108412
Daily std: 0.0075003074859417915
Annualized std: 0.11977030582676572
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.015896382732260593
Sharpe ratio: 0.1327239053330374
PRINTING STATS

Mean daily return: 4.484743494294696e-05
Annualized mean return: 0.011436095910451475
Daily std: 0.007462054778761349
Annualized std: 0.11915945907864363
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.011318448851627945
Sharpe ratio: 0.09498573540987562
PRINTING STATS

Mean daily return: 4.434565040042752e-05
Annualized mean return: 0.011308140852109018
Daily std: 0.007407103176290766
Annualized std: 0.11828195235696472
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.011190493793285489
Sharpe ratio: 0.09460863276515376
DISTANCE:
[[0.00000000e+00 4.80200266e-01 3.51216981e-01 7.28690433e-01
  5.38609704e-01 3.78423468e-01 3.13984427e-01 2.36542635e-01
  6.71669999e-01]
 [4.80200266e-01 0.00000000e+00 3.57413858e-01 7.03806374e-01
  5.96646125e-01 5.17838072e-01 5.00420388e-01 4.99525351e-01
  6.41791067e-01]
 [3.51216981e-01 3.57413858e-01 0.00000000e+00 6.95495832e-01
  4.88593842e-01 4.22017254e-01 3.75388158e-01 4.08668340e-01
  5.93324453e-01]
 [7.28690433e-01 7.03806374e-01 6.95495832e-01 7.45058060e-09
  7.26998773e-01 7.59359528e-01 7.35352173e-01 7.24020787e-01
  4.42005290e-01]
 [5.38609704e-01 5.96646125e-01 4.88593842e-01 7.26998773e-01
  0.00000000e+00 5.59321426e-01 5.21988293e-01 5.74950469e-01
  7.00525041e-01]
 [3.78423468e-01 5.17838072e-01 4.22017254e-01 7.59359528e-01
  5.59321426e-01 0.00000000e+00 3.23498726e-01 4.14128487e-01
  6.02928027e-01]
 [3.13984427e-01 5.00420388e-01 3.75388158e-01 7.35352173e-01
  5.21988293e-01 3.23498726e-01 0.00000000e+00 3.58598838e-01
  6.75818059e-01]
 [2.36542635e-01 4.99525351e-01 4.08668340e-01 7.24020787e-01
  5.74950469e-01 4.14128487e-01 3.58598838e-01 0.00000000e+00
  6.63423762e-01]
 [6.71669999e-01 6.41791067e-01 5.93324453e-01 4.42005290e-01
  7.00525041e-01 6.02928027e-01 6.75818059e-01 6.63423762e-01
  7.45058060e-09]]
PRINTING STATS

Mean daily return: 0.0006996369274010765
Annualized mean return: 0.1784074164872745
Daily std: 0.010946332735760638
Annualized std: 0.1747989161645637
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.17828976942845098
Sharpe ratio: 1.0199706802563973
PRINTING STATS

Mean daily return: 0.0007007365373650069
Annualized mean return: 0.17868781702807676
Daily std: 0.01096701470497457
Annualized std: 0.1751291807280493
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.17857016996925323
Sharpe ratio: 1.0196482917746716
PRINTING STATS

Mean daily return: 0.0008619053632294119
Annualized mean return: 0.21978586762350003
Daily std: 0.010685113705199888
Annualized std: 0.17062758275767687
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.2196682205646765
Sharpe ratio: 1.287413306889816
PRINTING STATS

Mean daily return: 0.000862134158632486
Annualized mean return: 0.21984421045128394
Daily std: 0.010683607652088083
Annualized std: 0.1706035330180988
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.2197265633924604
Sharpe ratio: 1.2879367707417309
PRINTING STATS

Mean daily return: 0.0007031694841035661
Annualized mean return: 0.17930821844640935
Daily std: 0.011140160300917848
Annualized std: 0.17789409416893873
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.17919057138758582
Sharpe ratio: 1.007287916019381
PRINTING STATS

Mean daily return: 0.0007032567944090536
Annualized mean return: 0.17933048257430867
Daily std: 0.011142412541071777
Annualized std: 0.17793005956002927
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.17921283551548514
Sharpe ratio: 1.0072094392517363
PRINTING STATS

Mean daily return: 0.000734526229790991
Annualized mean return: 0.18730418859670273
Daily std: 0.01104431172273957
Annualized std: 0.17636351511694784
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.1871865415378792
Sharpe ratio: 1.0613677177717542
PRINTING STATS

Mean daily return: 0.0007005737632821047
Annualized mean return: 0.1786463096369367
Daily std: 0.010963953175266918
Annualized std: 0.17508029201914363
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.17852866257811317
Sharpe ratio: 1.019695937899124
PRINTING STATS

Mean daily return: 0.0006996369274010765
Annualized mean return: 0.1784074164872745
Daily std: 0.010946332735760638
Annualized std: 0.1747989161645637
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.17828976942845098
Sharpe ratio: 1.0199706802563973
DISTANCE:
[[0.         0.43723579 0.28218431 0.6848469  0.41077984 0.29846105
  0.28857681 0.19712062 0.64619133]
 [0.43723579 0.         0.34219968 0.68437456 0.50497456 0.44084511
  0.45845162 0.48211365 0.64290833]
 [0.28218431 0.34219968 0.         0.68422183 0.32781951 0.30821829
  0.26626342 0.31908053 0.64032458]
 [0.6848469  0.68437456 0.68422183 0.         0.685714   0.66865546
  0.68981135 0.69366234 0.39137094]
 [0.41077984 0.50497456 0.32781951 0.685714   0.         0.43152725
  0.38528561 0.43268229 0.67614068]
 [0.29846105 0.44084511 0.30821829 0.66865546 0.43152725 0.
  0.2716225  0.30112485 0.60530429]
 [0.28857681 0.45845162 0.26626342 0.68981135 0.38528561 0.2716225
  0.         0.2716531  0.63830667]
 [0.19712062 0.48211365 0.31908053 0.69366234 0.43268229 0.30112485
  0.2716531  0.         0.6394848 ]
 [0.64619133 0.64290833 0.64032458 0.39137094 0.67614068 0.60530429
  0.63830667 0.6394848  0.        ]]
PRINTING STATS

Mean daily return: 0.0006259771174652121
Annualized mean return: 0.1596241649536291
Daily std: 0.005686564299627352
Annualized std: 0.09080714977972858
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15950651789480558
Sharpe ratio: 1.7565413987964764
PRINTING STATS

Mean daily return: 0.0006259771174652121
Annualized mean return: 0.1596241649536291
Daily std: 0.005686564299627352
Annualized std: 0.09080714977972858
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15950651789480558
Sharpe ratio: 1.7565413987964764
PRINTING STATS

Mean daily return: 0.0006165695162477456
Annualized mean return: 0.15722522664317512
Daily std: 0.005662204388484922
Annualized std: 0.09041815319353391
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.1571075795843516
Sharpe ratio: 1.7375667831665782
PRINTING STATS

Mean daily return: 0.0006165785272783458
Annualized mean return: 0.15722752445597818
Daily std: 0.005662227202433439
Annualized std: 0.0904185175030767
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15710987739715465
Sharpe ratio: 1.7375851953313506
PRINTING STATS

Mean daily return: 0.0006259771174652121
Annualized mean return: 0.1596241649536291
Daily std: 0.005686564299627352
Annualized std: 0.09080714977972858
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15950651789480558
Sharpe ratio: 1.7565413987964764
PRINTING STATS

Mean daily return: 0.0006259771174652121
Annualized mean return: 0.1596241649536291
Daily std: 0.005686564299627352
Annualized std: 0.09080714977972858
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15950651789480558
Sharpe ratio: 1.7565413987964764
PRINTING STATS

Mean daily return: 0.0006259771174652121
Annualized mean return: 0.1596241649536291
Daily std: 0.005686564299627352
Annualized std: 0.09080714977972858
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15950651789480558
Sharpe ratio: 1.7565413987964764
PRINTING STATS

Mean daily return: 0.0006259771174652121
Annualized mean return: 0.1596241649536291
Daily std: 0.005686564299627352
Annualized std: 0.09080714977972858
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15950651789480558
Sharpe ratio: 1.7565413987964764
PRINTING STATS

Mean daily return: 0.0006259771174652121
Annualized mean return: 0.1596241649536291
Daily std: 0.005686564299627352
Annualized std: 0.09080714977972858
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15950651789480558
Sharpe ratio: 1.7565413987964764
DISTANCE:
[[0.00000000e+00 5.70874828e-01 4.26218220e-01 7.10589025e-01
  4.77634165e-01 3.80068213e-01 3.31212839e-01 3.30741868e-01
  6.40943484e-01]
 [5.70874828e-01 7.45058060e-09 3.99970728e-01 6.51676841e-01
  5.80077574e-01 6.06620697e-01 5.72560231e-01 5.93115086e-01
  6.29036314e-01]
 [4.26218220e-01 3.99970728e-01 0.00000000e+00 6.70224362e-01
  4.34545461e-01 4.87293205e-01 4.35838090e-01 4.77534819e-01
  6.20042249e-01]
 [7.10589025e-01 6.51676841e-01 6.70224362e-01 0.00000000e+00
  6.88347580e-01 7.16612192e-01 6.95071205e-01 7.29009225e-01
  3.64665336e-01]
 [4.77634165e-01 5.80077574e-01 4.34545461e-01 6.88347580e-01
  0.00000000e+00 4.91521591e-01 4.60293415e-01 5.29908702e-01
  6.62494257e-01]
 [3.80068213e-01 6.06620697e-01 4.87293205e-01 7.16612192e-01
  4.91521591e-01 0.00000000e+00 3.01360728e-01 4.36938236e-01
  6.47622430e-01]
 [3.31212839e-01 5.72560231e-01 4.35838090e-01 6.95071205e-01
  4.60293415e-01 3.01360728e-01 0.00000000e+00 3.62759444e-01
  6.29982616e-01]
 [3.30741868e-01 5.93115086e-01 4.77534819e-01 7.29009225e-01
  5.29908702e-01 4.36938236e-01 3.62759444e-01 0.00000000e+00
  6.60328308e-01]
 [6.40943484e-01 6.29036314e-01 6.20042249e-01 3.64665336e-01
  6.62494257e-01 6.47622430e-01 6.29982616e-01 6.60328308e-01
  0.00000000e+00]]
PRINTING STATS

Mean daily return: -5.1244302087743755e-05
Annualized mean return: -0.013067297032374657
Daily std: 0.006925370841644289
Annualized std: 0.11058930386816673
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): -0.013184944091198187
Sharpe ratio: -0.11922440624923301
PRINTING STATS

Mean daily return: -5.123757424556773e-05
Annualized mean return: -0.013065581432619771
Daily std: 0.0069250949672491615
Annualized std: 0.11058489850735503
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): -0.013183228491443301
Sharpe ratio: -0.11921364191120978
PRINTING STATS

Mean daily return: -4.551435942453815e-05
Annualized mean return: -0.011606161653257228
Daily std: 0.0070465580993445175
Annualized std: 0.11252450918398464
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): -0.011723808712080758
Sharpe ratio: -0.10418893445615118
PRINTING STATS

Mean daily return: -4.556480926794569e-05
Annualized mean return: -0.011619026363326151
Daily std: 0.0070471835685133434
Annualized std: 0.11253449712564915
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): -0.011736673422149681
Sharpe ratio: -0.10429400514444231
PRINTING STATS

Mean daily return: -4.607980744382123e-05
Annualized mean return: -0.011750350898174413
Daily std: 0.007363962130187201
Annualized std: 0.11759304509613637
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): -0.011867997956997943
Sharpe ratio: -0.10092431867288958
PRINTING STATS

Mean daily return: -4.6081162118981754e-05
Annualized mean return: -0.011750696340340348
Daily std: 0.007363853620029716
Annualized std: 0.11759131232787698
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): -0.011868343399163877
Sharpe ratio: -0.10092874349485671
PRINTING STATS

Mean daily return: -5.244913835674431e-05
Annualized mean return: -0.013374530280969799
Daily std: 0.0069747750143697145
Annualized std: 0.11137822524072824

c:\Projects\portfolio\further_opts\objectives.py:29: ClusterWarning:

The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix

DISTANCE:
[[0.00000000e+00 5.64723465e-01 3.52466785e-01 7.83825743e-01
  4.44833844e-01 3.32214907e-01 3.12170928e-01 2.21777166e-01
  6.90257122e-01]
 [5.64723465e-01 7.45058060e-09 4.07632729e-01 7.30734348e-01
  6.13651136e-01 5.59903551e-01 5.60187352e-01 5.27737810e-01
  6.71708364e-01]
 [3.52466785e-01 4.07632729e-01 0.00000000e+00 7.74141507e-01
  4.28320657e-01 3.69601274e-01 3.39920536e-01 3.28341121e-01
  6.85338120e-01]
 [7.83825743e-01 7.30734348e-01 7.74141507e-01 0.00000000e+00
  7.65102121e-01 8.12236729e-01 8.05120891e-01 7.60480908e-01
  3.78255905e-01]
 [4.44833844e-01 6.13651136e-01 4.28320657e-01 7.65102121e-01
  0.00000000e+00 4.38189708e-01 4.31860355e-01 4.70362038e-01
  7.28222914e-01]
 [3.32214907e-01 5.59903551e-01 3.69601274e-01 8.12236729e-01
  4.38189708e-01 0.00000000e+00 2.20881108e-01 3.57931665e-01
  7.09114245e-01]
 [3.12170928e-01 5.60187352e-01 3.39920536e-01 8.05120891e-01
  4.31860355e-01 2.20881108e-01 0.00000000e+00 3.21666581e-01
  7.15515008e-01]
 [2.21777166e-01 5.27737810e-01 3.28341121e-01 7.60480908e-01
  4.70362038e-01 3.57931665e-01 3.21666581e-01 0.00000000e+00
  6.58578407e-01]
 [6.90257122e-01 6.71708364e-01 6.85338120e-01 3.78255905e-01
  7.28222914e-01 7.09114245e-01 7.15515008e-01 6.58578407e-01
  0.00000000e+00]]
PRINTING STATS

Mean daily return: 4.169728190086275e-05
Annualized mean return: 0.010632806884720002
Daily std: 0.0057181252526511605
Annualized std: 0.09131113778327789
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.010515159825896472
Sharpe ratio: 0.11515747236502126
PRINTING STATS

Mean daily return: 4.1571792587245766e-05
Annualized mean return: 0.01060080710974767
Daily std: 0.005727573122575274
Annualized std: 0.09146200816723796
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.01048316005092414
Sharpe ratio: 0.11461764574155991
PRINTING STATS

Mean daily return: 3.941398098528427e-06
Annualized mean return: 0.001005056515124749
Daily std: 0.005234340262281218
Annualized std: 0.08358571101116054
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.0008874094563012195
Sharpe ratio: 0.010616760275960693
PRINTING STATS

Mean daily return: 3.917123062450012e-06
Annualized mean return: 0.000998866380924753
Daily std: 0.005234124008744536
Annualized std: 0.0835822577191091
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.0008812193221012237
Sharpe ratio: 0.010543138533810554
PRINTING STATS

Mean daily return: 4.5509140390235345e-06
Annualized mean return: 0.0011604830799510012
Daily std: 0.005247770393630742
Annualized std: 0.08380017301049071
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.0010428360211274718
Sharpe ratio: 0.012444318235439945
PRINTING STATS

Mean daily return: 4.562243507974667e-06
Annualized mean return: 0.00116337209453354
Daily std: 0.005247806529296272
Annualized std: 0.0838007500507947
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.0010457250357100106
Sharpe ratio: 0.012478707351380012
PRINTING STATS

Mean daily return: 4.104127923243292e-05
Annualized mean return: 0.010465526204270395
Daily std: 0.005759083649287226
Annualized std: 0.09196519092716171
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.010347879145446865
Sharpe ratio: 0.11251952006104782
PRINTING STATS

Mean daily return: 4.1044179032691086e-05
Annualized mean return: 0.010466265653336226
Daily std: 0.005767296220024425
Annualized std: 0.09209633516500287
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.010348618594512696
Sharpe ratio: 0.11236732249955186
PRINTING STATS

Mean daily return: 4.178099202113528e-05
Annualized mean return: 0.010654152965389496
Daily std: 0.005711822864783456
Annualized std: 0.09121049671972567
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.010536505906565966
Sharpe ratio: 0.11551856733049985
DISTANCE:
[[7.45058060e-09 5.77757294e-01 4.32301086e-01 7.28835235e-01
  6.34208616e-01 4.03040181e-01 3.27373656e-01 2.48132094e-01
  6.61430336e-01]
 [5.77757294e-01 0.00000000e+00 3.36104358e-01 6.43876014e-01
  6.86077054e-01 5.95690323e-01 5.49590875e-01 5.85946278e-01
  6.02182975e-01]
 [4.32301086e-01 3.36104358e-01 0.00000000e+00 6.76504720e-01
  6.07863932e-01 4.68840061e-01 3.99766422e-01 4.35298346e-01
  5.83393833e-01]
 [7.28835235e-01 6.43876014e-01 6.76504720e-01 0.00000000e+00
  6.90510062e-01 7.61374003e-01 7.39595124e-01 7.43524204e-01
  4.51494828e-01]
 [6.34208616e-01 6.86077054e-01 6.07863932e-01 6.90510062e-01
  1.05367121e-08 6.00473068e-01 5.96652039e-01 6.15759481e-01
  6.95830041e-01]
 [4.03040181e-01 5.95690323e-01 4.68840061e-01 7.61374003e-01
  6.00473068e-01 0.00000000e+00 3.05413577e-01 3.93041716e-01
  6.46319921e-01]
 [3.27373656e-01 5.49590875e-01 3.99766422e-01 7.39595124e-01
  5.96652039e-01 3.05413577e-01 0.00000000e+00 2.93393847e-01
  6.55204221e-01]
 [2.48132094e-01 5.85946278e-01 4.35298346e-01 7.43524204e-01
  6.15759481e-01 3.93041716e-01 2.93393847e-01 0.00000000e+00
  6.68342160e-01]
 [6.61430336e-01 6.02182975e-01 5.83393833e-01 4.51494828e-01
  6.95830041e-01 6.46319921e-01 6.55204221e-01 6.68342160e-01
  0.00000000e+00]]
PRINTING STATS

Mean daily return: 0.0006249158816331938
Annualized mean return: 0.15935354981646443
Daily std: 0.005234517224537793
Annualized std: 0.08358853687178418
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.1592359027576409
Sharpe ratio: 1.9049968897277345
PRINTING STATS

Mean daily return: 0.0006250834950552739
Annualized mean return: 0.15939629123909485
Daily std: 0.005236246830824419
Annualized std: 0.083616156469287
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15927864418027132
Sharpe ratio: 1.90487880459772
PRINTING STATS

Mean daily return: 0.0006612613100608722
Annualized mean return: 0.1686216340655224
Daily std: 0.005526922271338859
Annualized std: 0.08825787102192346
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.16850398700669889
Sharpe ratio: 1.9092233367474056
PRINTING STATS

Mean daily return: 0.0006614727152317358
Annualized mean return: 0.16867554238409263
Daily std: 0.005525203596963318
Annualized std: 0.08823042599304154
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.1685578953252691
Sharpe ratio: 1.9104282159825765
PRINTING STATS

Mean daily return: 0.0006545260809299811
Annualized mean return: 0.1669041506371452
Daily std: 0.004946750858530051
Annualized std: 0.0789932765137248
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.16678650357832167
Sharpe ratio: 2.1114012601989374
PRINTING STATS

Mean daily return: 0.0006545957711558965
Annualized mean return: 0.1669219216447536
Daily std: 0.004947015540786721
Annualized std: 0.07899750315041773
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.16680427458593008
Sharpe ratio: 2.1115132495810793
PRINTING STATS

Mean daily return: 0.000643271442096292
Annualized mean return: 0.16403421773455445
Daily std: 0.005260282905588795
Annualized std: 0.08399998180322167
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.16391657067573093
Sharpe ratio: 1.9513881688655819
PRINTING STATS

Mean daily return: 0.0006199994169493075
Annualized mean return: 0.1580998513220734
Daily std: 0.005183784126199338
Annualized std: 0.0827783942589746
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.15798220426324988
Sharpe ratio: 1.9084956367841346
PRINTING STATS

Mean daily return: 0.0006249158816331938
Annualized mean return: 0.15935354981646443
Daily std: 0.005234517224537793
Annualized std: 0.08358853687178418
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.1592359027576409
Sharpe ratio: 1.9049968897277345
DISTANCE:
[[0.00000000e+00 6.41264378e-01 4.02159863e-01 7.02924525e-01
  6.15282172e-01 4.04986338e-01 4.05837117e-01 3.62776629e-01
  6.49001952e-01]
 [6.41264378e-01 0.00000000e+00 4.70969314e-01 7.03702130e-01
  6.95744874e-01 6.43609965e-01 6.23568108e-01 6.26841480e-01
  6.52148607e-01]
 [4.02159863e-01 4.70969314e-01 0.00000000e+00 6.75698684e-01
  5.47605317e-01 4.39854844e-01 4.08215753e-01 4.28134715e-01
  5.97626632e-01]
 [7.02924525e-01 7.03702130e-01 6.75698684e-01 0.00000000e+00
  6.28884972e-01 7.05999343e-01 6.94333200e-01 6.89835934e-01
  4.03179001e-01]
 [6.15282172e-01 6.95744874e-01 5.47605317e-01 6.28884972e-01
  0.00000000e+00 6.27326403e-01 6.29185262e-01 6.46826373e-01
  6.83295889e-01]
 [4.04986338e-01 6.43609965e-01 4.39854844e-01 7.05999343e-01
  6.27326403e-01 0.00000000e+00 3.01179616e-01 4.39872136e-01
  6.18090893e-01]
 [4.05837117e-01 6.23568108e-01 4.08215753e-01 6.94333200e-01
  6.29185262e-01 3.01179616e-01 0.00000000e+00 3.66887572e-01
  6.08873807e-01]
 [3.62776629e-01 6.26841480e-01 4.28134715e-01 6.89835934e-01
  6.46826373e-01 4.39872136e-01 3.66887572e-01 7.45058060e-09
  6.31395234e-01]
 [6.49001952e-01 6.52148607e-01 5.97626632e-01 4.03179001e-01
  6.83295889e-01 6.18090893e-01 6.08873807e-01 6.31395234e-01
  1.05367121e-08]]
PRINTING STATS

Mean daily return: 0.0005595587274599044
Annualized mean return: 0.14268747550227562
Daily std: 0.006544997438797816
Annualized std: 0.10451522772226467
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.1425698284434521
Sharpe ratio: 1.3641058011404086
PRINTING STATS

Mean daily return: 0.000559670922909534
Annualized mean return: 0.14271608534193117
Daily std: 0.006546659125923521
Annualized std: 0.10454176273774332
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.14259843828310764
Sharpe ratio: 1.3640332298665603
PRINTING STATS

Mean daily return: 0.0005713559469197658
Annualized mean return: 0.14569576646454027
Daily std: 0.0064631039949949514
Annualized std: 0.10320749429562043
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.14557811940571674
Sharpe ratio: 1.4105382598354033
PRINTING STATS

Mean daily return: 0.0005713614283703425
Annualized mean return: 0.14569716423443735
Daily std: 0.0064631460727382775
Annualized std: 0.10320816622329754
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.14557951717561382
Sharpe ratio: 1.4105426198605557
PRINTING STATS

Mean daily return: 0.0006691750005891577
Annualized mean return: 0.1706396251502352
Daily std: 0.0059631388065801896
Annualized std: 0.0952236904807221
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.17052197809141167
Sharpe ratio: 1.7907516210572998
PRINTING STATS

Mean daily return: 0.0006691690625065434
Annualized mean return: 0.17063811093916856
Daily std: 0.005964293359295566
Annualized std: 0.09524212720909263
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.17052046388034503
Sharpe ratio: 1.790389073377035
PRINTING STATS

Mean daily return: 0.0005641829901069547
Annualized mean return: 0.14386666247727345
Daily std: 0.00660362439545146
Annualized std: 0.10545142514367183
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.14374901541844992
Sharpe ratio: 1.3631775504465655
PRINTING STATS

Mean daily return: 0.0005622226454397929
Annualized mean return: 0.1433667745871472
Daily std: 0.006564658925775286
Annualized std: 0.10482919649124041
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.14324912752832367
Sharpe ratio: 1.366500291169299
PRINTING STATS

Mean daily return: 0.0005595746007413741
Annualized mean return: 0.1426915231890504
Daily std: 0.006545232532355961
Annualized std: 0.10451898186533277
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.14257387613022687
Sharpe ratio: 1.3640955316033008
DISTANCE:
[[0.00000000e+00 6.33675774e-01 3.87124817e-01 7.21550565e-01
  5.29469166e-01 3.84149576e-01 3.64999675e-01 2.45940094e-01
  6.40088773e-01]
 [6.33675774e-01 0.00000000e+00 4.62688877e-01 7.19507398e-01
  7.30221342e-01 6.03239383e-01 6.06707852e-01 6.41791109e-01
  6.44498179e-01]
 [3.87124817e-01 4.62688877e-01 0.00000000e+00 6.99842855e-01
  5.43597809e-01 3.76343620e-01 3.57899608e-01 4.31707848e-01
  5.93639449e-01]
 [7.21550565e-01 7.19507398e-01 6.99842855e-01 0.00000000e+00
  6.63309744e-01 7.12233790e-01 7.13527262e-01 7.30846714e-01
  4.63400374e-01]
 [5.29469166e-01 7.30221342e-01 5.43597809e-01 6.63309744e-01
  0.00000000e+00 5.67860307e-01 5.44619712e-01 5.17086618e-01
  6.72341831e-01]
 [3.84149576e-01 6.03239383e-01 3.76343620e-01 7.12233790e-01
  5.67860307e-01 0.00000000e+00 2.50237222e-01 4.25754840e-01
  6.44382279e-01]
 [3.64999675e-01 6.06707852e-01 3.57899608e-01 7.13527262e-01
  5.44619712e-01 2.50237222e-01 0.00000000e+00 3.89758845e-01
  6.25985742e-01]
 [2.45940094e-01 6.41791109e-01 4.31707848e-01 7.30846714e-01
  5.17086618e-01 4.25754840e-01 3.89758845e-01 7.45058060e-09
  6.46416125e-01]
 [6.40088773e-01 6.44498179e-01 5.93639449e-01 4.63400374e-01
  6.72341831e-01 6.44382279e-01 6.25985742e-01 6.46416125e-01
  7.45058060e-09]]
PRINTING STATS

Mean daily return: 0.0008312937598086149
Annualized mean return: 0.2119799087511968
Daily std: 0.007622910039182492
Annualized std: 0.12172811159996959
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.21186226169237327
Sharpe ratio: 1.7404546814018447
PRINTING STATS

Mean daily return: 0.000831568135475449
Annualized mean return: 0.2120498745462395
Daily std: 0.007625840818547588
Annualized std: 0.12177491239334057
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.21193222748741597
Sharpe ratio: 1.7403603363134572
PRINTING STATS

Mean daily return: 0.0009924448091594145
Annualized mean return: 0.2530734263356507
Daily std: 0.008291689182283506
Annualized std: 0.13240765809188423
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.25295577927682716
Sharpe ratio: 1.910431639092118
PRINTING STATS

Mean daily return: 0.0009924767125177975
Annualized mean return: 0.2530815616920384
Daily std: 0.008292099179502575
Annualized std: 0.1324142052224396
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.2529639146332148
Sharpe ratio: 1.9103986177938124
PRINTING STATS

Mean daily return: 0.0007703006454617681
Annualized mean return: 0.19642666459275088
Daily std: 0.007009042484190808
Annualized std: 0.11192543285162614
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.19630901753392735
Sharpe ratio: 1.7539268112026356
PRINTING STATS

Mean daily return: 0.0007702801684557128
Annualized mean return: 0.19642144295620678
Daily std: 0.007009054703367334
Annualized std: 0.11192562797622765
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.19630379589738325
Sharpe ratio: 1.7538771007751417
PRINTING STATS

Mean daily return: 0.0008309647823740502
Annualized mean return: 0.2118960195053828
Daily std: 0.007644402730831747
Annualized std: 0.12207132236255454
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.21177837244655928
Sharpe ratio: 1.7348740748262954
PRINTING STATS

Mean daily return: 0.0008300906653854158
Annualized mean return: 0.21167311967328103
Daily std: 0.007610059029650704
Annualized std: 0.12152289743445839
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.2115554726144575
Sharpe ratio: 1.7408692277811832
PRINTING STATS

Mean daily return: 0.0008314239423658442
Annualized mean return: 0.21201310530329026
Daily std: 0.007624300601096474
Annualized std: 0.12175031709301383
Daily risk-free rate: 0.0001176470588235294
Annualized risk-free rate: 0.03
Excess return (annualized): 0.21189545824446673
Sharpe ratio: 1.7404099086048748

                var_alpha      cvar    sharpe   sortino  mean_return        md
ER              -0.007370 -0.012318  0.835452  1.158390     0.000427 -0.130364
ER_cvar         -0.007378 -0.012330  0.835440  1.158381     0.000428 -0.130376
sharpe          -0.007283 -0.012521  0.850173  1.137961     0.000397 -0.130632
sharpe_cvar     -0.007282 -0.012520  0.850376  1.138222     0.000397 -0.130623
momentum_based  -0.007395 -0.012294  0.886040  1.209286     0.000351 -0.130657
momentum_cvar   -0.007395 -0.012295  0.885990  1.209387     0.000351 -0.130661
risk_parity     -0.007451 -0.012397  0.849843  1.175785     0.000441 -0.129830
hrp_weights     -0.007345 -0.012332  0.836150  1.159175     0.000428 -0.130332
equal_weights   -0.007367 -0.012314  0.835541  1.158505     0.000427 -0.130352

In [5]:
num_strats = 9
from plotly.subplots import make_subplots
fig = make_subplots(rows=1, cols=2)
L = list(range(len(total_costs[0])))
for i in range(num_strats):
    fig.add_trace(go.Scatter(x=L, y=total_costs[i], name=f"cost - {df.index[i]}"), row=1, col=1)
    fig.add_trace(go.Scatter(x=L, y=total_stress_values[i], name=f"stress - {df.index[i]}"), row=1, col=2)
fig.show()

In [6]:
num_strats = 9

fig = make_subplots(rows=1, cols=1)
L = list(range(len(total_costs[0])))
for i in range(num_strats):
    fig.add_trace(go.Scatter(x=L, y=track_cash_allocs[i], name=df.index[i]), row=1, col=1)
fig.show()

In [5]:
from stress_testing import stress_test
from rollingwindow_and_eval import compute_statistics_rolling

start_train = "2019-10-01"
end_train = "2020-02-01"
end_valid = "2020-03-01"

window_size = 252

all_corrs, all_volas = compute_statistics_rolling(returns, window_size, window_size)
global_corr_mean = np.mean(all_corrs)
global_corr_std = np.std(all_corrs)
global_vola_mean = np.mean(all_volas)
global_vola_std = np.std(all_volas)

Sigma = np.cov(returns, rowvar=False)

df_merged

# stats, cumreturns_all, ws, stress_values = stress_test(
#     df_merged, start_train, end_train, end_valid,
#     gamma, alpha, lambda_, m_params, Sigma,
#     min_weight, stress_corr_weight, global_corr_mean,
#     global_corr_std, global_vola_mean,
#     global_vola_std, max_cash_alloc,
#     cash_alloc_param, risk_free)

# stats

,Price_snp,Vol_snp,Price_china,Vol_china,Price_em,Vol_em,Price_gold,Vol_gold,Price_india,Vol_india,Price_mscieurope,Vol_mscieurope,Price_smallcapeurope,Vol_smallcapeurope,Price_ussmallcap,Vol_ussmallcap,Price_silver,Vol_silver
Date,,,,,,,,,,,,,,,,,,
2015-06-04,193.48,79.92K,6.29,3.59K,24.41,29.05K,102.72,5.42K,14.10,410.18K,3966.5,0.55K,157.48,0.12K,251.28,0.83K,1036.25,2.48K
2015-06-05,192.96,268.78K,6.32,NaN,24.23,1.37K,103.72,11.29K,14.26,140.22K,3906.0,52.00K,155.25,2.35K,250.14,NaN,1039.50,8.35K
2015-06-08,192.07,96.24K,6.48,30.00K,24.16,6.35K,102.95,3.62K,13.93,126.13K,3896.0,NaN,153.55,2.50K,250.78,6.15K,1028.75,0.47K
2015-06-09,191.68,114.16K,6.30,37.71K,24.07,15.51K,103.01,12.21K,13.84,384.04K,3876.0,0.13K,153.47,0.07K,249.49,NaN,1026.75,1.28K
2015-06-10,193.84,150.58K,6.41,0.36K,24.35,232.44K,103.60,1.38K,14.05,187.14K,3912.5,NaN,155.62,0.25K,252.62,11.49K,1016.50,0.41K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-16,717.87,67.65K,5.93,1.40M,47.39,412.44K,415.60,6.27K,24.95,64.88K,9404.0,9.04K,331.05,5.34K,599.70,2.92K,5702.00,441.38K
2026-03-17,721.96,80.25K,5.92,280.55K,47.99,265.78K,416.04,3.16K,24.95,14.36K,9465.0,4.24K,333.90,3.29K,604.70,2.04K,5669.00,438.25K
2026-03-18,716.48,132.07K,5.86,554.45K,47.58,982.99K,406.02,3.75K,24.66,44.02K,9399.0,7.31K,334.35,6.66K,602.00,3.01K,5501.00,391.98K
2026-03-19,707.36,123.68K,5.79,1.52M,46.76,555.16K,381.58,10.85K,24.25,96.35K,9142.0,7.39K,325.30,3.85K,594.10,6.24K,5022.00,1.07M
2026-03-20,703.62,195.33K,5.72,3.28M,45.92,399.90K,380.50,7.46K,23.82,49.17K,9036.5,22.65K,320.00,10.25K,591.20,16.87K,4998.00,462.77K